name    'coralnexus-xinetd'
version '0.4.0'
source 'git://github.com/coralnexus/puppet-xinetd'
author 'Adrian Webb'
license 'Apache Version 2.0'
summary 'Xinetd Module'
description 'Xinetd system management.'
project_page 'http://github.com/coralnexus/puppet-xinetd'
dependency 'coralnexus/corl', '>= 0.4.0'
